// Generated by CIRCT firtool-1.139.0
`ifndef layers_Adder_Verification_Assert
  `define layers_Adder_Verification_Assert
  `include "layers-Adder-Verification.sv"
`endif // not def layers_Adder_Verification_Assert
