// Generated by CIRCT firtool-1.139.0
`ifndef layers_RegFile_Verification_Assert
  `define layers_RegFile_Verification_Assert
  `include "layers-RegFile-Verification.sv"
`endif // not def layers_RegFile_Verification_Assert
